config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/diceroll', to: 'random#show'
  get '/filter', to: 'random#filter'

  resources :movies do
	collection do
    	get '/:id/tags', to: 'movies#manage_tags'
  	end
  end

  resources :tags do
  	collection do
  		get '/:str/search', to: 'tags#search'
  	end
  end

  resources :directors, :movie_directors
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
	#has_many :movie_directors, dependant: :destroy

	def movies
		MovieDirector.where(director_id: id).map{ |m| Movie.find(m.movie_id)}
	end
end

app/models/movie.rb
require 'httparty'
class Movie < ApplicationRecord
	has_many :movie_director
	has_many :tag
	belongs_to :rating
	validates_numericality_of :year, greater_than: 1888, less_than: Time.now.year
	validates_numericality_of :runtime, greater_than: 0
	#validates :movie_title, :year, :best_picture_winner, :best_picture_nominee, :runtime, :seen, :foreign, presence: true
	
	after_save :winner_is_nominee

	def poster
		response = HTTParty.get("http://www.omdbapi.com/?apikey=99f518b9&t=" + URI.encode(movie_title) + "&y=" + year.to_s)
		response["Poster"] ? response["Poster"] : false
	end

	def directors
		directors = []
		MovieDirector.where(movie_id: id).each do |md|
			d = md.director
			directors.push(d) unless directors.include?(d)
		end
		directors
	end

	def director_exists?(director_id)
		directors.include?(Director.find(director_id))
	end

	def winner_is_nominee
		best_picture_nominee = true if best_picture_winner?
	end
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
	belongs_to :movie
	belongs_to :director
end

app/models/movie_tag.rb
class MovieTag < ApplicationRecord
	belongs_to :movie
	belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
	has_many :movie
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
	helper_method :sort_column, :sort_direction

	def index
		#@directors = Director.all.sort_by { |d| d[:name].sub(/^the /i,"").downcase }
		@directors = Director.order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 10)
	end

	def new
	end

	def create
		Director.create(director_params);
		redirect_to directors_path
	end

	def edit
		@director = Director.find(params[:id])
	end

	def update
		Director.find(params[:id]).update!(director_params)
		redirect_to directors_path
	end

	def director_params
		params.require(:director).permit(:name)
	end

	def destroy
	    @director = Director.find(params[:id])
	    @director.destroy

	    redirect_to directors_path
	end

	private 

	def sort_column
		Director.column_names.include?(params[:sort]) ? params[:sort] : "name"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController	
	helper_method :sort_column, :sort_direction

	def index
		#@movies = Movie.all.sort_by { |m| m[:movie_title].sub(/^the /i,"").downcase }.paginate(page: params[:page], per_page: 2)
		@movies = Movie.order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 10)
	end

	def new
	end

	def create
		m = Movie.create(movie_params)
		MovieDirector.create({movie_id: m.id, director_id: params[:movie_director][:director_id]})
		redirect_to movies_path
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		save_tags if params["tags"].present?
		save_movie if params["movie_details"].present?
	end

	def save_movie
		Movie.find(params[:id]).update!(movie_params)
		redirect_to movies_path
	end

	def save_tags
		params["movie_tags"].each do |tag_id|
			MovieTag.create({movie_id: params[:id], tag_id: tag_id})
		end
		redirect_to movies_path
	end

	def manage_tags
		@movie = Movie.find(params[:id])
	end

	def movie_params
		params.require(:movie).permit(:movie_title, :year, :best_picture_winner, :best_picture_nominee, :runtime, :seen, :subtitles, :rating_id)
	end

	def director_params
		params.require(:movie_director).permit(:director_id)
	end

	def destroy
	    @movie = Movie.find(params[:id])
	    @movie.destroy

	    redirect_to movies_path
	end

	private 

	def sort_column
		Movie.column_names.include?(params[:sort]) ? params[:sort] : "movie_title"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/controllers/random_controller.rb
class RandomController < ApplicationController
	def show
		get_random_movie
		get_dropdownlist_values
	end

	def get_random_movie
		movie_list = Movie.all.to_a
		movie_list = movie_list.select{ |m| m.director_exists?(params[:director]) } if param_present(:director)
		movie_list = movie_list.select{ |m| m.rating_id == params[:rating].to_i } if param_present(:rating)
		movie_list = movie_list.select{ |m| m.year >= params[:year].to_i && m.year < params[:year].to_i + 10 } if param_present(:year)
		movie_list = filter_bool(movie_list, :subtitles) if param_present(:subtitles)
		movie_list = filter_bool(movie_list, :seen) if param_present(:seen)
		movie_list = filter_runtime(movie_list) if param_present(:runtime_min)
		@movie = movie_list.count == 0 ? false : movie_list[rand(0..movie_list.count-1)]
	end

	def get_dropdownlist_values
		@directors = Director.all.sort_by { |d| d[:name].sub(/^the /i,"").downcase }
		get_year_list
		@ratings = Rating.all
		@bool_list = [["Any",0], ["No",1], ["Yes",2]]
		@runtimes_min = [["Any",0], ["30 minutes",30], ["1 hour", 60], ["1 hour 30 minutes", 90], ["2 hours", 120], ["2 hours 30 minutes", 150], ["3 hours", 180]]
		@runtimes_max = [["Any",999], ["30 minutes",30], ["1 hour", 60], ["1 hour 30 minutes", 90], ["2 hours", 120], ["2 hours 30 minutes", 150], ["3 hours", 180]]
	end

	def filter_bool(list, attribute)
		if params[attribute] == "1"
			list.select{ |m| !m[attribute] }
		elsif params[attribute] == "2"
			list.select{ |m| m[attribute] }
		else
			list
		end
	end

	def filter_runtime(list)
		min = params[:runtime_min]
		max = params[:runtime_max]
		min < max ? list.select{ |m| m.runtime >= min.to_i && m.runtime <= max.to_i } : list
	end

	def get_year_list
		movies_by_year = Movie.all.order(:year)
		first = movies_by_year.first.year/10*10
		last = movies_by_year.last.year/10*10

		@decade_array = []
		(first..last).step(10) do |decade|
			@decade_array.push({"id": decade, "decade": decade.to_s+"s"})
		end
	end

	def param_present(p)
		!params[p].nil? && !params[p].empty?
	end

	def filter
		redirect_to diceroll_path(filter_params)
	end

	def filter_params
		params.require(:filter).permit(:rating, :director, :year, :subtitles, :seen, :runtime_min, :runtime_max)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	helper_method :sort_column, :sort_direction

	def index
		@tags = Tag.order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 10)
	end

	def new
	end

	def create
		Tag.create(tag_params);
		redirect_to tags_path
	end

	def edit
		@tag = Tag.find(params[:id])
	end

	def update
		Tag.find(params[:id]).update!(tag_params)
		redirect_to tags_path
	end

	def tag_params
		params.require(:tag).permit(:tag_name)
	end

	def destroy
	    @tag = Tag.find(params[:id])
	    @tag.destroy

	    redirect_to tags_path
	end

	def search
		tags = Tag.where("tag_name LIKE ?", "#{params[:str]}%").order('tag_name ASC').limit(5).map{ |t| [t.tag_name, t.id] }
		render json: {success: true, data: tags}
	end

	private 

	def sort_column
		Tag.column_names.include?(params[:sort]) ? params[:sort] : "tag_name"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/director_helper.rb
module DirectorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/random_helper.rb
module RandomHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/directors/edit.html.haml
%h1#movie_header="Edit Director"
=form_for @director, html: { class: "center", id: "new_director" } do |d|
	.attributes
		.attribute
			.one_quarter="Name"
			=d.text_field :name, class: "one_half"
		=link_to 'Delete', @director,  method: :delete, data: { confirm: 'Are you sure?' }
	.form_button
		=d.submit "Save", class: "btn", id: "save_director"
#movies_list
	%h2="Movies"
	-@director.movies.sort_by { |m| m[:movie_title].sub(/^the /i,"") }.each do |m|
		.director_movie="#{m.movie_title}"

app/views/directors/index.html.haml
.list_title
	%h1="Directors"
=link_to "+ Add new director", new_director_path, id: "add_director_btn"
=will_paginate @directors
%table.list{cellspacing: 0}
	%tr.header_row
		%th=sortable "name", "Name"
		%th="# of Movies"
		%th
	-@directors.each do |director|
		%tr
			%td=link_to "#{director.name}", edit_director_path(director.id)
			%td="#{MovieDirector.where(director_id: director.id).count}"
			%td=link_to 'Delete', director,  method: :delete, data: { confirm: 'Are you sure?' }

app/views/directors/new.html.haml
%h1#director_header="Add a Director"
=form_for Director.new, html: { class: "center", id: "new_director" } do |d|
	.attributes
		.attribute
			.one_quarter="Name"
			=d.text_field :name, class: "one_half"
	.form_button
		=d.submit "Add", class: "btn", id: "add_director"

app/views/home/index.html.haml
#center-container
	#logo-container
		=image_tag "dice.jpg"
		#app-title="Movie Dice"
	#home-buttons
		#top-row.home-row
			=link_to "Movies", movies_path, {class: "home-btn"}
			=link_to "Directors", directors_path, {class: "home-btn"}
			.home-btn="Tags"
		#second-row.home-row
			=link_to "Roll the Dice", diceroll_path, {class: "home-btn alt"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roll the Dice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if params[:controller] != "home" %>
    	<div id="header">
        <a class="header-btn alt" href="/">Home</a>
        <a class="header-btn" href="/diceroll">Roll the Dice</a>
        <a class="header-btn" href="/movies">Movies</a>
        <a class="header-btn" href="/directors">Directors</a>
        <a class="header-btn" href="/tags">Tags</a>
    	</div>
    <% end %>
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/edit.html.haml
%h1#movie_header="Edit Movie"
=form_for @movie, html: { class: "center", id: "new_movie" } do |m|
	.attributes
		.attribute
			.one_quarter="Title"
			=m.text_field :movie_title, class: "one_half"
		.attribute
			.one_quarter="Year"
			=m.number_field :year, in: 1888..Time.now.year, class: "one_quarter"
		.attribute
			.one_quarter="Runtime (minutes)"
			=m.number_field :runtime, min: 0, class: "one_quarter"
		.attribute
			.one_quarter="Rating"
			=m.select :rating_id, options_for_select(Rating.all.collect {|r| [r[:rating],r[:id]]}), class: "one_quarter"
		.attribute
			.one_half="Have you seen it already?"
			=m.check_box :seen, class: "one_quarter"
		.attribute
			.one_half="Does it have subtitles?"
			=m.check_box :subtitles, class: "one_quarter"
		.attribute
			.one_half="Was it nominated for Best Picture?"
			=m.check_box :best_picture_nominee, class: "one_quarter"
		.attribute
			.one_half="Did it win Best Picture?"
			=m.check_box :best_picture_winner, class: "one_quarter"
		=link_to 'Delete', @movie,  method: :delete, data: { confirm: 'Are you sure?' }
	.form_button
		=m.submit "Save", class: "btn", id: "save_movie", name: "movie_details"

app/views/movies/index.html.haml
.list_title
	%h1="Movies"
=link_to "+ Add new movie", new_movie_path, id: "add_movie_btn"
=will_paginate @movies
%table.list.fullwidth{cellspacing: 0}
	%tr.header_row
		%th=sortable "movie_title", "Movie Title"
		%th="Dir."
		%th=sortable "year", "Year"
		%th=sortable "rating", "Rating"
		%th=sortable "runtime", "Runtime"
		%th=sortable "best_picture_winner", "BP Winner"
		%th=sortable "best_picture_nominee", "BP Nominee"
		%th=sortable "seen", "Seen"
		%th=sortable "subtitles", "Subtitles"
		%th="Tags"
		%th
	-@movies.each do |movie|
		%tr
			%td=link_to "#{movie.movie_title}", edit_movie_path(movie.id)
			%td
				-movie.directors.each do |d|
					%div="#{d.name}"
			%td="#{movie.year}"
			%td="#{movie.rating.rating}"
			%td="#{movie.runtime} minutes"
			%td=movie.best_picture_winner ? "Yes" : "No"
			%td=movie.best_picture_nominee ? "Yes" : "No"
			%td=movie.seen ? "Yes" : "No"
			%td=movie.subtitles ? "Yes" : "No"
			%td=link_to "View", "/movies/#{movie.id}/tags"
			%td=link_to 'Delete', movie,  method: :delete, data: { confirm: 'Are you sure?' }

app/views/movies/manage_tags.html.haml
%h1#movie_header="#{@movie.movie_title}"
=form_for @movie, html: { class: "center", id: "edit_tag" } do |m|
	.checkbox_collection
		-Tag.all.order(:tag_name).each do |t|
			.checkbox
				=check_box_tag "movie_tags[]", t.id, MovieTag.where(movie_id: @movie.id, tag_id: t.id).count > 0
				#{t.tag_name}
	.form_button
		=m.submit "Save", class: "btn", id: "save_tag", name: "tags"

app/views/movies/new.html.haml
%h1#movie_header="Add a Movie"
=form_for Movie.new, html: { class: "center", id: "new_movie" } do |m|
	.attributes
		.attribute
			.one_quarter="Title"
			=m.text_field :movie_title, class: "one_half"
		=fields_for :movie_director do |md|
			.attribute
				.one_quarter="Director"
				=md.select :director_id, options_from_collection_for_select(Director.all.order(:name), "id", "name", params[:director_id]), class: "one_half"
		.attribute
			.one_quarter="Year"
			=m.number_field :year, in: 1888..Time.now.year, class: "one_quarter"
		.attribute
			.one_quarter="Runtime (minutes)"
			=m.number_field :runtime, min: 0, class: "one_quarter"
		.attribute
			.one_quarter="Rating"
			=m.select :rating_id, options_for_select(Rating.all.collect {|r| [r[:rating],r[:id]]}), class: "one_quarter"
		.attribute
			.one_half="Have you seen it already?"
			=m.check_box :seen, class: "one_quarter"
		.attribute
			.one_half="Does it have subtitles?"
			=m.check_box :subtitles, class: "one_quarter"
		.attribute
			.one_half="Was it nominated for Best Picture?"
			=m.check_box :best_picture_nominee, class: "one_quarter"
		.attribute
			.one_half="Did it win Best Picture?"
			=m.check_box :best_picture_winner, class: "one_quarter"
	.form_button
		=m.submit "Add", class: "btn", id: "add_movie", name: "movie_details"

app/views/random/_random_filters.haml
#filters_container
	%h1="Filters"
	=form_tag filter_path, method: :get, id: "controls" do
		.filter
			Rating: 
			=select_tag "filter[rating]", options_from_collection_for_select(@ratings, "id", "rating", params[:rating]), include_blank: "Any"
		.filter
			Director: 
			=select_tag "filter[director]", options_from_collection_for_select(@directors, "id", "name", params[:director]), include_blank: "Any"
		.filter
			Subtitles: 
			=select_tag "filter[subtitles]", options_for_select(@bool_list, params[:subtitles])
		.filter
			Year: 
			=select_tag "filter[year]", options_for_select(@decade_array.collect {|d| [ d[:decade], d[:id] ] }, params[:year]), include_blank: "Any"
		.filter
			Seen Before: 
			=select_tag "filter[seen]", options_for_select(@bool_list, params[:seen])
		.filter
			Best Picture Winner: 
			=select_tag "filter[best_picture_winner]", options_for_select(@bool_list, params[:best_picture_winner])
		.filter
			Best Picture Nominee: 
			=select_tag "filter[best_picture_nominee]", options_for_select(@bool_list, params[:best_picture_nominee])
		.filter
			Runtime: from
			=select_tag "filter[runtime_min]", options_for_select(@runtimes_min, params[:runtime_min])
			&nbsp;to&nbsp; 
			=select_tag "filter[runtime_max]", options_for_select(@runtimes_max, params[:runtime_max])
		.filter
			Tags: 
			=text_field_tag "random-tags"
		=submit_tag "Roll the Dice", class: "btn", style: "text-align: center;"

app/views/random/_random_selection.haml
#random_movie
	#random_movie_text="Your random movie is"
	-if @movie
		-poster_url = @movie.poster
		-if poster_url
			=image_tag poster_url, class: 'movie_poster', alt: @movie.movie_title
		-else
			=image_tag "poster_unavailable.jpg", class: 'movie_poster', alt: @movie.movie_title
			#random_movie_title="#{@movie.movie_title}"
	-else
		=image_tag "ralph_wiggum.jpg", {id: "nose_pick"}
		%h2="Stop being picky"
		#nose_pick_sub
			You filtered out all of your movies. Lower your standards a little bit there, 
			%span.pink="princess."

app/views/random/show.html.haml
.half.left
	= render partial: "random/random_selection"
.half.right
	= render partial: "random/random_filters"
.clear

app/views/tags/edit.html.haml
%h1#movie_header="Edit Tag"
=form_for @tag, html: { class: "center", id: "edit_tag" } do |t|
	.attributes
		.attribute
			.one_quarter="Tag Name"
			=t.text_field :tag_name, class: "one_half"
		=link_to 'Delete', @tag,  method: :delete, data: { confirm: 'Are you sure?' }
	.form_button
		=t.submit "Save", class: "btn", id: "save_tag"

app/views/tags/index.html.haml
.list_title
	%h1="Tags"
=link_to "+ Add new tag", new_tag_path, id: "add_tag_btn"
=will_paginate @tags
%table.list{cellspacing: 0}
	%tr.header_row
		%th=sortable "tag_name", "Tag"
		%th="# of Movies"
		%th
	-@tags.each do |tag|
		%tr
			%td=link_to "#{tag.tag_name}", edit_tag_path(tag.id)
			%td="#{MovieTag.where(tag_id:tag.id).count}"
			%td=link_to 'Delete', tag,  method: :delete, data: { confirm: 'Are you sure?' }

app/views/tags/new.html.haml
%h1#director_header="Add a Tag"
=form_for Tag.new, html: { class: "center", id: "new_tag" } do |t|
	.attributes
		.attribute
			.one_quarter="Tag Name"
			=t.text_field :tag_name, class: "one_half"
	.form_button
		=t.submit "Add", class: "btn", id: "add_tag"